//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WellTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellTest
    {
        public int ID { get; set; }
        public string WELLID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.DateTime> TIMESTART { get; set; }
        public Nullable<System.DateTime> TIMESTOP { get; set; }
        public Nullable<double> BEAN { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
    
        public virtual Well Well { get; set; }
    }
}
